
driftfile /var/lib/chrony/chrony.drift
maxdistance 20.0
makestep 0.1 -1
rtcsync
logdir /var/log/chrony
local stratum 13 
manual

# Сервер №1 SRV-ASUTP-KC3-OSN
server 172.17.13.134 iburst minpoll 1 maxpoll 3 version 3 prefer

# Сервер №2 SRV-ASUTP-KC3-REZ
server 172.17.13.135 iburst minpoll 1 maxpoll 3 version 3

# Коммутатор основной A2
allow 172.17.13.147

# Коммутатор резервный А3
allow 172.17.13.148
